name = "alx-hackathon-api"
main = "cloudflare-worker.js"
compatibility_date = "2024-03-14"

[[d1_databases]]
binding = "DB"
database_name = "alx_hackathon_db"
database_id = "876e6035-b76a-4850-b3d4-7a9c7ed7558c"
